### PR TITLE
Replaced file references with NuGet references

### PR DESCRIPTION
**Pull request by luminescent**
Hi

I have replaced all references to the files in the relative paths with NuGet references. I have not changed anything in the .fsx files, where the .dlls are opened directly from that base folder bin. 
Some inconsistent line endings and/or tabs where changed too (I have a Visual Studio extension that does that automatically).

### CODE REVIEW

**Comment by luminescent** [comment]
I could also make the upgrade to Akka 1.0, as the 0.8 version which is
currently used is a beta, check everything is still working, and make
another pull request, what do you think?

**Comment by rikace** [comment]
Thanks
I am exactly doing the same thing, and I am replacing the FluentCOnfig with
the Helios.

Go Ahead and fI will accept your request!

Thanks again
Riccardo

**Comment by luminescent** [comment]
Oh, in that case I will wait :). I did a pull a few minutes ago and seems
there were a few merge issues, some of the packages files and a couple of
fsproj were not actually merged and contained those ">>>>> head" things,
for those projects where my version from the first pull request were still
on 0.8 but you've already made the upgrade to 1.0 on your end. I've fixed
everything locally and did the upgrade for all of the projects, but the
solution still does not compile because of FluentConfig being removed from
1.0.0, so not sure it's any use in pushing anything from my end now. Quite
a long list of files were changed and seems like it will just make things
more difficult for you when merging, since you are already doing similar
things.

I could pull everything in a fresh copy once you are done on your end, I'm
quite happy to poke around things and learn Akka in the process.

**Comment by rikace** [comment]
I will do a push shortly
Take a look after 

I'll talk you later

**Comment by rikace** [comment]
I did some changes but I have still to fix few things.
I will push few more changes tomorrow and I will send an email right after.

Thanks
Riccardo

**Comment by luminescent** [comment]
Great, thank you. I can try this on Ubuntu as well,   though might take a
bit to install everything, as I have not have used Mono on there so far and
I expect Nuget to be capricious.

**Comment by rikace** [comment]
I never try to run Akka.Net http://akka.net/ on ubuntu but I was successfully on Mac and RaspberryPi too.
The deployment is the tricky part because you have to use scp copy but once figure it out it is pretty simple.

Let me know if I can help.

Riccardo

**Comment by luminescent** [comment]
Hi 
Seems like I am doing some stuff incorrectly? I have pulled the latest version and had to do some tricks to get it to build (but not in all scenarios). 

On Windows:
- some files were still corrupted and had to be manually fixed: 
  - RemoteAkka.Server.Console/RemoteAkka.Server.Console.fsproj
  - RemoteAkka.Server.Console/packages.config
  - RemoteAkka.Shared/RemoteAkka.Shared.fsproj
  - RemoteAkka.Shared/packages.config
- I had to manually add a non-empty RELEASE_NOTES.md in the folder root so that the build.bat would pass to the actual building
- the Persistence project did not build not matter what I have tried. I suspect some sort of incompatibility between the Akka.Persistence libraries and Akka. I tried to use the dev version for 1.0.0 from NuGet but it did not improve things
- once I escaped Persistence from build, I was able to build everything successfully in Visual Studio 2013 Community Edition; though had to manually set NuGet to automatically restore packages as a first step (at this point I can't recall if I ran paket install before hand, probably not)
- despite the previous point, I never actually managed to have the build.bat running correctly, as it keeps on complaining it can not find the Akka references, although I go and check the paths it is using and the files are there (in the bin subfolder of the solution root). 

On Ubuntu
- had to install mono-devel in order to get mono-complete and F# to work (this is not mentioned in the official documentation)
- had to do some tricks for paket install to work (e.g. mark it as executable)
- had to change paket.dependencies to include all the packages that were required
- on Ubuntu the folder structure for the downloaded NuGet packages is different than on Windows, the version number does not appear in the folder name containing each package, hence all of the references to dlls in packages, from the fsproj files, have to be changed  
- the build.sh tripped on one last project no matter what I tried. Again something to do with missing references to one of the other projects, but can't recall which one it was. 

I can come back with the build logs from both systems if you think it's worth it (but since Visual Studio builds work in Windows I don't really care much for build.bat).

Not sure what you meant with deployments and scp copy, you meant the RemoteDeployRouter project?

**Comment by rikace** [comment]
Hi,

I have fixed the build in local and I will puttee changes shortly, by tomorrow.
I have also fixed the Persistence Project, there were few updated API no compatible with old one.

I am glad you were able to make it work on UBUNTU.

I am on Skype during the day, let chat sometime.

Thanks
Riccardo

**Comment by luminescent** [comment]
Hi

I have seen you pushed some updates I did not have so gave it a try with
those, then got overzealous attempting to understand and fix stuff. Long
story short, I figured out why none of the command line builds were working
(the .cmd and .sh), but building from Visual Studio was. It was really
bugging me as the error message the command line builds were throwing were
saying that libraries are missing from paths where they obviously were.
The projects that were failing were the ones with NuGet references added to
packages.config, but the corresponding assembly reference was still
pointing to the bin subfolder of the root. So once everything was
consistent I was able to build from Visual Studio, from build.cmd and also
just by running msbuild in the root folder.

However this was not gonna help on Ubuntu, because of the paths difference
I explained in my previous email, so I thought it would be a nice and
useful learning experiment to migrate the solution to paket as per their
guide http://fsprojects.github.io/Paket/paket-convert-from-nuget.html.
This would then allow the same code to work in both systems. I've managed
to convert the project but encountered quite a plethora of bugs in paket,
some documented (e.g. access denied and folder not empty), others not (it
broke the .sln and all of the .fsproj files containing references to
Google.Serialization by introducing duplicate links to the license files).
The workaround for the known bugs was to run paket update -v until it
worked (a few times), then do paket install --hard -v until it worked (yet
few more times). For the others, I had to manually go and fix the .sln and
.fsproj files. Once that was done, Visual Studio was again happy to build
the solution (though seemed to be taking longer). But the build.cmd stopped
working; first issue was that now it seemed to have changed from building
Release|Any CPU to Release|x64, so I had to create that platform. Then, and
I am assuming the root cause for the other thing, I discovered that FAKE
started using F# 3.0 instead of 3.1, and the build failed saying it's
missing some references and not recognizing types (such as Lazy<>). Not
sure how it ended up doing that, and this is where I have stopped for now.

I have pushed all of my changes into my fork, in case you find some use for
them. Quite a lot of files have changed and, a word of warning, I have
omitted to add the debug and release folders to the .ignore file.

I have added you on Google+, as most of the times I am on Ubuntu, hence no
Skype, glad to chat when you are free (I'm on GMT+1 - London).

**Comment by rikace** [comment]
Hi,

I will be happy to chat with you.

I have updated few things, I am also trying to remote deploy the assembly-dependencies with an Actor deployment using “Vagabond”.

Have you tried to create a new F# project in Ubuntu using the “ProjectScafold”/
 https://github.com/fsprojects/ProjectScaffold https://github.com/fsprojects/ProjectScaffold 

I am curious if it works on Ubuntu… I guess I could try my self.
I am not an expert in Ubuntu but I have a VM pre-configured.

Let chat sometime, I am curious to know what’s your final goal? 
I would like to help

Riccardo

**Pull request merged**
